<?php 

switch(isset($_PARAMS['language'])){		
	case 'es':
		$_FORM_TEXTS = array(
			'title' 	=> 'Datos del jugador',
			'loading' 	=> 'Cargando',
			'submitdetails' => 'Enviar datos',
			'required'	=> 'Datos obligatorios',
			'needed'	=> 'Por favor rellene primero la siguiente informaci&oacute;n',
			'dontclose'	=> 'No cierre esta ventana',
			'secure'	=> 'Esta transacci&oacute;n es segura.',
			'secureinfo'	=> 'Protegemos su informaci&oacute;n financiera con los m&aacute;s avanzados sistemas de seguridad y prevenci&oacute;n de fraude.',
			'cardtype'	=> 'Tipo de tarjeta',
			'cardnumber'	=> 'N&uacute;mero de tarjeta',
			'cvvinfo'	=> '\'CVV\' significa \'n&uacute;mero de verificaci&oacute;n\'. Es un n&uacute;mero de 3 o 4 cifras situado al final de la serie de n&uacute;meros en la parte de detr&aacute;s de la tarjeta.',
			'please'	=> 'Por favor, introduzca el n&uacute;mero para ayudarnos a estar seguros de que esta tarjeta no es usada fraudulentamente.',
			'selectlanguage' => 'Seleccione idioma',
			'expirydate'	=> 'Fecha de vencimiento',
			'owner'		=> 'Nombre del propietario',
			'totalamount'	=> 'El importe total debitado a su tarjeta ser&aacute; de',
			'month'		=> 'Mes',
			'year'		=> 'A&ntilde;o',
			'month_jan'	=> 'Enero',
			'month_feb'	=> 'Febrero',
			'month_mar'	=> 'Marzo',
			'month_apr'	=> 'Abril',
			'month_may'	=> 'Mayo',
			'month_jun'	=> 'Junio',
			'month_jul'	=> 'Julio',
			'month_aug'	=> 'Agosto',
			'month_sep'	=> 'Septiembre',
			'month_oct'	=> 'Octubre',
			'month_nov'	=> 'Noviembre',
			'month_dev'	=> 'Diciembre',
			'cancel'	=> 'Cancelar',
			'proceed'	=> 'Aceptar',
			'error'		=> 'Error',
			'new'		=> 'Nueva tarjeta',
			'back'		=> 'Volver',
			'new_card'	=>	'Debe registrar una nueva tarjeta primero',
			'alert_error1'	=> 'Debe rellenar todos los datos marcados en rojo.',
			'alert_error2'	=> 'Revise los datos marcados en rojo.',
			'loading' 		=> 'Cargando'
		);
		break;
	
	default: 
		$_FORM_TEXTS = array(
			'title' 	=> 'Player Details',
			'title2' 	=> 'Card Payment Details',
			'loading' 		=> 'Loading',
			'submitdetails' => 'Submit Details',
			'required'	=> 'Required fields',
			'needed'	=> 'Please fill the following information first',
			'dontclose'	=> 'Do not close this window',
			'secure'	=> 'This transaction is secure.',
			'secureinfo'	=> 'We protect your financial information with industry-leading security and fraud prevention systems.',
			'cardtype'	=> 'Card Type',
			'cardnumber'	=> 'Card Number',
			'cvvinfo'	=> '\'CVV\' stands for \'card verification value\'. It is a three- or four-digit number located at the end of the series of numbers on the back of your card, or in case of American Express cards on the front at the top right.',
			'please'	=> 'Please enter the number in order to help us be sure that your card is not being used fraudulently.',
			'selectlanguage'=> 'Select Language',
			'expirydate'	=> 'Expiry Date',
			'owner'		=> 'Cardholder\'s Name',
			'totalamount'	=> 'Total amount that will be charged to your card is',
			'month'		=> 'Month',
			'year'		=> 'Year',
			'month_jan'	=> 'January',
			'month_feb'	=> 'February',
			'month_mar'	=> 'March',
			'month_apr'	=> 'April',
			'month_may'	=> 'May',
			'month_jun'	=> 'June',
			'month_jul'	=> 'July',
			'month_aug'	=> 'August',
			'month_sep'	=> 'September',
			'month_oct'	=> 'October',
			'month_nov'	=> 'November',
			'month_dev'	=> 'December',
			'cancel'	=> 'Cancel',
			'proceed'	=> 'Proceed',
			'error'		=> 'Error',
			'new'		=> 'New card',
			'back'		=> 'Back',
			'new_card'	=>	'You must register a new card first.',
			'alert_error1'	=> 'You must fill in all fields marked in red.',
			'alert_error2'	=> 'Check data marked in red.',
			'loading' 		=> 'Loading'
		); 
		break;
}


?>
